version: "3"
services:
  gocd-server:
    build: .
    volumes:
      - ../data/artifacts:/godata/artifacts
      - ../data/config:/godata/config
      - ../data/db:/godata/db
      - ../data/logs:/godata/logs
    ports:
      - 8153:8153
      - 8154:8154
